### PR TITLE
Update Gemfile

### PR DESCRIPTION
**Pull request by bollavasu**
Google cloud implementation for OneOps

### CODE REVIEW

**Comment by lkhusid** [comment]
Why do you need this change?     What does it fix?

**Comment by bollavasu** [comment]
We could not start rails server because of json 1.8.1 version. If we change json version from 1.8.1 to 1.8.3 then only rails server is started

**Comment by lkhusid** [comment]
Sorry for delay.    I see, I guess no harm in bumping the patch version of this gem.   I will test going to 1.8.6 (latest patch for this minor version) and will merge it soon.   I might end up rejecting this PR only to create a new one with 1.8.6.

**Comment by bollavasu** [comment]
Ok, thank you very much

**Comment by mosabua** [comment]
Please resubmit at https://github.com/oneops/oneops if necessary.

**Pull request closed without merging**
